#!/bin/bash
set -u
: ${CKAN_INIT:=}
: ${CKAN_ADMIN:=}
: ${CKAN_ADMIN_PASSWORD:=}
: ${CKAN_ADMIN_EMAIL:=}

if [[ -n "$CKAN_INIT"  && "$CKAN_INIT" == "true" ]]; then

    if [ -z "$CKAN_ADMIN" ]; then
        CKAN_ADMIN=admin
    fi

    if [ -z "$CKAN_ADMIN_PASSWORD" ]; then
        CKAN_ADMIN_PASSWORD=ckan
    fi

    if [ -z "$CKAN_ADMIN_EMAIL" ]; then
        CKAN_ADMIN_EMAIL=admin@localhost
    fi


    # add an admin user if only the default and/or harvest user exists
    if [ $("$CKAN_HOME"/bin/paster --plugin=ckan user list -c "$CKAN_CONFIG/ckan.ini" | grep -Ev '^name=(harvest|default)$' | grep '^name=' | wc -l) -eq '0' ]; then
        "$CKAN_HOME"/bin/paster --plugin=ckan user -c "$CKAN_CONFIG/ckan.ini" add $CKAN_ADMIN "password=$CKAN_ADMIN_PASSWORD" "email=$CKAN_ADMIN_EMAIL"
        "$CKAN_HOME"/bin/paster --plugin=ckan sysadmin -c "$CKAN_CONFIG/ckan.ini" add $CKAN_ADMIN
    fi

fi
