#!/bin/sh
set -eux
echo "PGPASSWORD=${POSTGRES_PASSWORD}" >> /etc/crontab

echo "0 19 * * 0 root psql -h postgis -U ckanadmin ckan < /scripts/cleanup_extents.sql 2>&1 | /usr/bin/logger -t cleanup_extents" >> /etc/crontab
echo "10 19 * * 0 root psql -h postgis -U ckanadmin ckan < /scripts/cleanup_user_activity.sql 2>&1 | /usr/bin/logger -t cleanup_user_activity" >> /etc/crontab
echo "20 19 * * 0 root psql -h postgis -U ckanadmin ckan < /scripts/cleanup_old_harvest_objects.sql 2>&1 | /usr/bin/logger -t cleanup_old_harvest_objects" >> /etc/crontab
echo "30 19 * * 0 root psql -h postgis -U ckanadmin ckan < /scripts/cleanup_old_package_extras.sql 2>&1 | /usr/bin/logger -t old_package_extras" >> /etc/crontab
echo "40 19 * * 0 root psql -h postgis -U ckanadmin ckan < /scripts/cleanup_old_package_revisions.sql 2>&1 | /usr/bin/logger -t cleanup_old_package_revisions" >> /etc/crontab
echo "50 19 * * 0 root psql -h postgis -U ckanadmin ckan < /scripts/cleanup_old_resources.sql 2>&1 | /usr/bin/logger -t cleanup_old_resources" >> /etc/crontab
echo "0 20 * * 0 root psql -h postgis -U ckanadmin ckan < /scripts/cleanup_old_tags.sql 2>&1 | /usr/bin/logger -t cleanup_old_tags" >> /etc/crontab

echo "25 0 * * * root psql -h postgis -U ckanadmin ckan < /scripts/cleanup_duplicates.sql 2>&1 | /usr/bin/logger -t cleanup_duplicates" >> /etc/crontab
echo "30 0 * * * root /usr/lib/ckan/default/bin/paster --plugin=ckan search-index rebuild -r -c /etc/ckan/default/ckan.ini 2>&1 | /usr/bin/logger -t search-index" >> /etc/crontab
